[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cli-todo-starter"
version = "0.1.0"
description = "Minimal Python CLI To-Do app"
authors = [{name = "Student"}]
requires-python = ">=3.9"

[project.scripts]
todo = "cli_todo.cli:main"
